-- Esquema inicial del dominio de tickets de compra (CLAUDE §5).
-- El dominio legado Casa/Concepto/Cuenta/Detalle no se migra: queda fuera del MVP.

create table merchant (
    id     bigint generated by default as identity primary key,
    name   varchar(120) not null,
    tax_id varchar(32),
    constraint uq_merchant_name unique (name)
);

create table category (
    id   bigint generated by default as identity primary key,
    name varchar(80) not null,
    constraint uq_category_name unique (name)
);

create table receipt (
    id                  uuid          primary key,
    merchant_id         bigint        not null references merchant (id),
    purchased_at        timestamp     not null,
    store_name          varchar(160),
    store_address       varchar(240),
    store_phone         varchar(40),
    operation_number    varchar(60),
    invoice_number      varchar(60),
    currency            varchar(3)    not null default 'EUR',
    total_amount        numeric(12, 2) not null,
    payment_method      varchar(60),
    card_last4          varchar(4),
    source_type         varchar(16)   not null,
    source_filename     varchar(260),
    gmail_message_id    varchar(120),
    gmail_attachment_id varchar(512),
    content_hash        varchar(64)   not null,
    parser_version      varchar(40)   not null,
    parsing_status      varchar(16)   not null,
    raw_text            text,
    imported_at         timestamptz   not null,
    constraint ck_receipt_source_type check (source_type in ('GMAIL', 'UPLOAD', 'SAMPLE')),
    constraint ck_receipt_parsing_status check (parsing_status in ('PARSED', 'REVIEW', 'ERROR')),
    constraint ck_receipt_total_not_negative check (total_amount >= 0)
);

-- Antiduplicado en tres capas (CLAUDE §5). Indices parciales: los campos
-- opcionales solo restringen cuando estan presentes.

-- 1. La factura simplificada, cuando es fiable, identifica el ticket dentro del comercio.
create unique index uq_receipt_invoice
    on receipt (merchant_id, invoice_number)
    where invoice_number is not null;

-- 2. El mismo adjunto de Gmail no se importa dos veces.
create unique index uq_receipt_gmail_attachment
    on receipt (gmail_message_id, gmail_attachment_id)
    where gmail_message_id is not null and gmail_attachment_id is not null;

-- 3. Red de seguridad final: el hash SHA-256 del PDF.
create unique index uq_receipt_content_hash on receipt (content_hash);

create index ix_receipt_purchased_at on receipt (purchased_at desc);

create table receipt_item (
    id              uuid           primary key,
    receipt_id      uuid           not null references receipt (id) on delete cascade,
    line_number     integer        not null,
    raw_description varchar(240)   not null,
    normalized_name varchar(240),
    quantity        numeric(10, 3) not null,
    unit            varchar(16)    not null,
    unit_price      numeric(12, 2),
    weight_kg       numeric(10, 3),
    price_per_kg    numeric(12, 2),
    line_total      numeric(12, 2) not null,
    category_id     bigint         references category (id),
    category_source varchar(16)    not null,
    constraint uq_receipt_item_line unique (receipt_id, line_number),
    constraint ck_receipt_item_unit check (unit in ('UNIT', 'KG')),
    constraint ck_receipt_item_category_source
        check (category_source in ('RULE', 'MANUAL', 'UNASSIGNED'))
);

create index ix_receipt_item_receipt on receipt_item (receipt_id);
create index ix_receipt_item_category on receipt_item (category_id);
create index ix_receipt_item_normalized_name on receipt_item (normalized_name);

-- Desglose de IVA del ticket. El texto del PDF lo trae ya tabulado, asi que
-- extraerlo no complica el parser (CLAUDE §6).
create table receipt_tax_line (
    id           uuid           primary key,
    receipt_id   uuid           not null references receipt (id) on delete cascade,
    rate_percent numeric(5, 2)  not null,
    taxable_base numeric(12, 2) not null,
    tax_amount   numeric(12, 2) not null,
    total_amount numeric(12, 2) not null,
    constraint uq_receipt_tax_rate unique (receipt_id, rate_percent)
);

-- Regla persistida para no recategorizar el mismo producto una y otra vez (CLAUDE §5).
create table product_rule (
    id              bigint       generated by default as identity primary key,
    merchant_id     bigint       not null references merchant (id),
    match_text      varchar(240) not null,
    normalized_name varchar(240),
    category_id     bigint       not null references category (id),
    active          boolean      not null default true,
    created_at      timestamptz  not null default now(),
    constraint uq_product_rule_match unique (merchant_id, match_text)
);

create index ix_product_rule_lookup on product_rule (merchant_id, active);
