-- Registro de importaciones y pipeline de carpeta.
--
-- Cada intento de importar un PDF deja constancia, con su estado y, si falló, el motivo.
-- Antes el resultado era transitorio: se devolvía en la respuesta HTTP y se perdía, así que
-- la interfaz no podía mostrar un historial ni dejar abrir un error para consultarlo.

create table import_record (
    id                bigint       generated by default as identity primary key,
    source            varchar(32)  not null,
    original_filename varchar(260) not null,
    sha256            varchar(64)  not null,
    processing_status varchar(16)  not null,
    error_message     text,
    receipt_id        uuid         references receipt (id) on delete set null,
    stored_path       varchar(1024),
    imported_at       timestamptz  not null,
    constraint ck_import_source check (source in ('MERCADONA')),
    constraint ck_import_status
        check (processing_status in ('PENDING', 'PROCESSING', 'PROCESSED', 'DUPLICATE', 'ERROR'))
);

-- Un mismo PDF solo puede quedar procesado una vez. El índice es parcial a propósito:
-- los intentos marcados DUPLICATE o ERROR sí pueden repetirse con el mismo hash, porque el
-- historial debe poder mostrar que se volvió a intentar.
create unique index uq_import_sha256_processed
    on import_record (sha256)
    where processing_status = 'PROCESSED';

create index ix_import_record_imported_at on import_record (imported_at desc);
create index ix_import_record_status on import_record (processing_status);
create index ix_import_record_receipt on import_record (receipt_id);

-- El origen del ticket pasa a ser el canal por el que entró el fichero. GMAIL ya no existe
-- (el backend no habla con Gmail) y SAMPLE no lo usaba nadie.
update receipt set source_type = 'UPLOAD' where source_type not in ('FOLDER', 'UPLOAD');

alter table receipt drop constraint if exists ck_receipt_source_type;

alter table receipt
    add constraint ck_receipt_source_type check (source_type in ('FOLDER', 'UPLOAD'));
